SET C51INC=C:\Keil_v5\C51\Inc;C:\Keil_v5\C51\Inc\Atmel
SET C51LIB=C:\Keil_v5\C51\Lib
SET CPU_TYPE=AT89S52
SET CPU_VENDOR=Microchip
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x01F78A40
"C:\Keil_v5\C51\BIN\A51.EXE" @".\Objects\STARTUP._ia"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\lcd.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\delay.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\i2c.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\eeprom.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\main.__i"
"C:\Keil_v5\C51\BIN\BL51.EXE" @".\Objects\EXECUT~1.LNP"
"C:\Keil_v5\C51\BIN\OH51.EXE" ".\Objects\executable" 
